#! /bin/bash
#
# Generated by the utility: /z/tools/collect_git_checked_out_branch_recusively.sh 
#
# Checkout each git repository to the given branch/commit or list them
#

mode=h;
while getopts ":hlrc" opt ; do
  #echo opt+arg = "$opt$OPTARG"
  case "$opt$OPTARG" in
  l )
    mode=l;
    ;;

  c )
    mode=c;
    ;;

  r )
    mode=r;
    ;;

  * )
    ;;
  esac
done

if test "$mode" = "h" ; then
  cat <<EOH
checkout_to_known_git_branches_recursive.sh options

Options:

-h      : print this help
-l      : LIST the branch/commit for each git repository (directory) registered in this script.
-c      : CHECKOUT each git repository to the BRANCH registered in this script.
-r      : CHECKOUT/REVERT each git repository to the COMMIT registered in this script.

Note:

Use the '-r' option to set each repository to an exact commit position, which is useful if,
for instance, you wish to reproduce this registered previous software state (which may
represent a software release) which you wish to analyze/debug.

EOH
  exit 1;
fi

if test "$mode" = "l" ; then
  cat <<EOH

Git repository directory                    :: commit hash                         / branch name
--------------------------------------------::--------------------------------------------------
EOH
fi



# args: DIR COMMIT [BRANCH]
git_repo_checkout_branch() {
  if test "$mode" = "c" || test "$mode" = "r" ; then
    if test -d "$1" ; then
      pushd "$1"                                                               2> /dev/null  > /dev/null
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
      if test "$mode" = "c" ; then
        if test -n "$3" ; then
          # make sure the branch is created locally and is a tracking branch, if it isn't already:
          # https://www.cyberciti.biz/faq/bash-remove-whitespace-from-string/
          current_branch=$( git branch --show-current )
          if test -z "$current_branch" -o "$current_branch" != "$3" ; then
            git checkout "$3"
          fi

          shopt -s extglob
          remote_branch=$( git branch -vv --list $3 '--format=%(upstream)' )
          # Trim leading whitespaces
          remote_branch="${remote_branch##*( )}"
          # Trim trailing whitespaces
          remote_branch="${remote_branch%%*( )}"
          echo "=${remote_branch}="
          shopt -u extglob

          if test -z "$remote_branch" ; then
            echo "No remote branch registered for local branch: $3 --> setting up the remote."
            git branch --track "$3" "remotes/origin/$3"                          2> /dev/null  > /dev/null
            git branch --set-upstream-to=remotes/origin/$3 $3                    2> /dev/null  > /dev/null
            git checkout "$3"
          fi
        else
          current_branch=$( git branch --show-current )
          echo "=${current_branch}="
          if test -z "$current_branch" -o "$current_branch" != "master" ; then
            # checkout to the first of `master` or `main` in case we're not checked out to either right now:
            if test "$current_branch" != "main" -a "$current_branch" != "master" ; then
              echo "Checking out to master/main:"
              git checkout master
              if test $? -ne 0 ; then
                git checkout main
              fi
            fi
          fi
        fi
      else
        git checkout "$2"
      fi
      popd                                                                     2> /dev/null  > /dev/null
    fi
  else
    if test -d "$1" ; then
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
    else
      printf "%-43s :: %s / %s\n" "[DIRECTORY DOES NOT EXIST!] $1" "$2" "$3"
    fi
  fi
}


#
# Make sure we switch to the utility directory as all the relative paths for the repositories
# are based off that path!
#
pushd $(dirname $0)                                                            2> /dev/null  > /dev/null



#
# The registered repositories:
#

git_repo_checkout_branch "../libs/accumulators"                   9d9e5dae2202660f57e2dc91efb620aa001525b3 master    
git_repo_checkout_branch "../libs/algorithm"                      32c5a6327cfdca5d41ce0f1d8849b811886daa2f master    
git_repo_checkout_branch "../libs/align"                          5ad7df63cd792fbdb801d600b93cad1a432f0151 master    
git_repo_checkout_branch "../libs/any"                            8292e1831811488bee57feee690b818b0821cddd master    
git_repo_checkout_branch "../libs/array"                          31b9fdd39708feb4e8a8802d7738f16533b7d7a6 master    
git_repo_checkout_branch "../libs/asio"                           5320c5fa84d24e20ab00258a004fd1d0ca3186dd master    
git_repo_checkout_branch "../libs/assert"                         fa72d2f0fd5adaf128b6fef80e0168fc1cc1bbb9 master    
git_repo_checkout_branch "../libs/assign"                         b452220f5de0f6205433c08cee63742102a424d2 master    
git_repo_checkout_branch "../libs/atomic"                         037f686d36e4a54fe3319d72a88d39ac77dbd06e master    
git_repo_checkout_branch "../libs/beast"                          84115e5b13dfd4e173e59133d11860f900ae3aca master    
git_repo_checkout_branch "../libs/bimap"                          c81ecb5b9e01c0e8bf4b4d4f83888f09e79fe75d master    
git_repo_checkout_branch "../libs/bind"                           a541a8d5c16920e1836d09299915890d687efe36 master    
git_repo_checkout_branch "../libs/callable_traits"                2a56a3a2496cdb66496f844db55085dd992d5e49 master    
git_repo_checkout_branch "../libs/charconv"                       a3767c440cace86a0529c7b3888d4a3eae438231 master    
git_repo_checkout_branch "../libs/chrono"                         ef510872039483dc66b7b2263c43c273a9aaecd6 master    
git_repo_checkout_branch "../libs/circular_buffer"                a08a5b55ee82e0c2487523471379ac53a23935dc master    
git_repo_checkout_branch "../libs/cobalt"                         a832aec118e7525c3f2e7db55a8a8b8cc6ba9df9 master    
git_repo_checkout_branch "../libs/compat"                         61b464c3eec8a2d3e4aae1275b5844a411caedae master    
git_repo_checkout_branch "../libs/compatibility"                  7be386ad98083806f805c6d1e2450e09ae10250f master    
git_repo_checkout_branch "../libs/compute"                        cf7907574d6159cd43e6cf687a7b656278c61dd0 master    
git_repo_checkout_branch "../libs/concept_check"                  0ef7f2b5daeaa125a53d98affba8f40091d24b17 master    
git_repo_checkout_branch "../libs/config"                         57c5cbacfd3d1a9cbf182f03b3f87c29ffdacca4 master    
git_repo_checkout_branch "../libs/container"                      866fd30df1ab723e2104e3de504f4a8c116f2c41 master    
git_repo_checkout_branch "../libs/container_hash"                 b8179488b20eb1373bdbf5c7fcca963f072512df master    
git_repo_checkout_branch "../libs/context"                        46effe4588a6edd64d49a853454b5f67f7196e57 master    
git_repo_checkout_branch "../libs/contract"                       eca93d24b5d3bb909ed64c12b5feb5296c5cc070 master    
git_repo_checkout_branch "../libs/conversion"                     9d64c899df6fc62ea35523a8423ad0d7ac6c6078 master    
git_repo_checkout_branch "../libs/convert"                        0dd7a76b1c051c048b4991b7aa9c8b5aeb5776ee master    
git_repo_checkout_branch "../libs/core"                           7178a52909c039e2a9ae8411c033607290ea5541 master    
git_repo_checkout_branch "../libs/coroutine"                      8b09bf7d0e8a13d1ef59aaff02a84d42acb034f3 master    
git_repo_checkout_branch "../libs/coroutine2"                     dbbf042e0a9081b4119d491b788ae0fe7c03192a master    
git_repo_checkout_branch "../libs/crc"                            75146a958410c789381a4609166c754d35548e2d master    
git_repo_checkout_branch "../libs/date_time"                      75be56b4c85d8e2dcbc22a1eb251d18cc942fceb master    
git_repo_checkout_branch "../libs/describe"                       ddff876eeaab5f08844c4c8e88d1679f86ae8210 master    
git_repo_checkout_branch "../libs/detail"                         a54b2619f8f75861836114d02a3fc70c7c9b3474 master    
git_repo_checkout_branch "../libs/dll"                            cb815af05788b115d6273cd559c1ae6c11efc913 master    
git_repo_checkout_branch "../libs/dynamic_bitset"                 b96250c3c66d310b51555fbf532245c47d71c1b9 master    
git_repo_checkout_branch "../libs/endian"                         c0b5c80603b8de7eeea8724c9a4f2761c3df06f2 master    
git_repo_checkout_branch "../libs/exception"                      ece51fe0f7b8273ffc3fa626c3d1442f7af24ef9 master    
git_repo_checkout_branch "../libs/fiber"                          7838ab09d700214e3d7dd7104fce241ca7552336 master    
git_repo_checkout_branch "../libs/filesystem"                     fb0229b54de3bd692612a70777cce0db439eb37e master    
git_repo_checkout_branch "../libs/flyweight"                      a4fee292a5a71733796371443754849b2de62e5a master    
git_repo_checkout_branch "../libs/foreach"                        cc2f75ae30492b9de69b3b692f5c59afcb7dea5e master    
git_repo_checkout_branch "../libs/format"                         66075102416bc5d0f8e0bd151a19013dadbf94ce master    
git_repo_checkout_branch "../libs/function"                       f6b538dbed2e3047dcbd09eb3f5c7f1ffa90d0a9 master    
git_repo_checkout_branch "../libs/function_types"                 6fba35ace59e9e7b1c3007ca6246a42ed6ead145 master    
git_repo_checkout_branch "../libs/functional"                     6a573e4b8333ee63ee62ce95558c3667348db233 master    
git_repo_checkout_branch "../libs/fusion"                         94cab8e4bbc8065d18481b96c0a8feea0491cf6e master    
git_repo_checkout_branch "../libs/geometry"                       c5ebb039ad27c0f7b941f27da93ec216ac924ca5 master    
git_repo_checkout_branch "../libs/gil"                            36c715a8dc8a22ad21b7018cebacf5e73186efdd master    
git_repo_checkout_branch "../libs/graph"                          198616d896e0db612d507baed7f8e01c38809066 master    
git_repo_checkout_branch "../libs/graph_parallel"                 5520a5617d2763c48a06a4ff277ad76e665c7cf3 master    
git_repo_checkout_branch "../libs/hana"                           275ee334d4c406643e9f560c40f9b73638cd9c7e master    
git_repo_checkout_branch "../libs/headers"                        5c0228ed90ff32a54ba0b015ddae2b170062dcb1 master    
git_repo_checkout_branch "../libs/heap"                           7db5d9db6615b40239a8bb9383a12bd56924bd07 master    
git_repo_checkout_branch "../libs/histogram"                      824719d91579fca4ddb93b01e5c1d26e592c68b5 master    
git_repo_checkout_branch "../libs/hof"                            63ac019fca325038bfb4f56db17fbb281d2b5f49 master    
git_repo_checkout_branch "../libs/icl"                            2741c3a1b7b79f7326360c26c3e1588b385c9e53 master    
git_repo_checkout_branch "../libs/integer"                        2dfe66886d71b9a341433ea8b6ff225cc07da80b master    
git_repo_checkout_branch "../libs/interprocess"                   1739eeb8871487074e1843d88e43dd2ae5f0786b master    
git_repo_checkout_branch "../libs/intrusive"                      ec5e251f547aa850e0e41a9ed204a08581931a6b master    
git_repo_checkout_branch "../libs/io"                             342e4c6d10d586058818daa84201a2d301357a53 master    
git_repo_checkout_branch "../libs/iostreams"                      3173bcac127b1e23b05d7ed07a93ad8cadc5ae3f master    
git_repo_checkout_branch "../libs/iterator"                       4b40364d6d110b130207bc498791e00050f94d6b master    
git_repo_checkout_branch "../libs/json"                           9b654f7b1a96aecf74729e41334752f9143d39cf master    
git_repo_checkout_branch "../libs/lambda"                         af16036c576b14896e8c62cf0bd0a1f8235ce07b master    
git_repo_checkout_branch "../libs/lambda2"                        865eb98c9ca7d37e95ed062c4d4197b15c1e3d18 master    
git_repo_checkout_branch "../libs/leaf"                           6633c368f1ee2d9c26fdd86e3ed11517c22f4e4c master    
git_repo_checkout_branch "../libs/lexical_cast"                   1c89e3a56cda1b4709c31f561d71e37cd6ef3619 master    
git_repo_checkout_branch "../libs/local_function"                 258aeaa6c1a9618c02ca4e4af2890e70833035f0 master    
git_repo_checkout_branch "../libs/locale"                         52cf8f8a5e23fc6ab5e3d5c8c5657f178ec35e90 master    
git_repo_checkout_branch "../libs/lockfree"                       26a0337fdd9d8541e0ea84e2a07563e383844391 master    
git_repo_checkout_branch "../libs/log"                            6366d73335d298c8c5c7f7bd80f6931fedb0df1b master    
git_repo_checkout_branch "../libs/logic"                          9b8703a2d6623405323b892f1d126a6b17ca1651 master    
git_repo_checkout_branch "../libs/math"                           f1b0b95a04f56717b3454cb599e0647770c5852e master    
git_repo_checkout_branch "../libs/metaparse"                      0ef448c1a7ce22b5de514f9cd504c323c28f4379 master    
git_repo_checkout_branch "../libs/move"                           a2bb5c88539fe78cd0177c9f43bab1cb01681450 master    
git_repo_checkout_branch "../libs/mp11"                           e5da96b9b655fd0c310136b88f90f6243ce5705f master    
git_repo_checkout_branch "../libs/mpi"                            a6c2dd23d15e6f88f346abb77d96989f12f3be1b master    
git_repo_checkout_branch "../libs/mpl"                            2b7937ac6fb7a5193784225cfb80d4b14f4f1a12 master    
git_repo_checkout_branch "../libs/msm"                            33e77cbfc70956d4b99f3dfc9c1e83848fe2550b master    
git_repo_checkout_branch "../libs/multi_array"                    0c5348bef71b890c4bd06eff1ee5ebda69e7b27a master    
git_repo_checkout_branch "../libs/multi_index"                    1e952cd5a7b7582bdfb26f7b2b45b667153d9cea master    
git_repo_checkout_branch "../libs/multiprecision"                 7e847d47e8196a5cd727445db027a1d0dd940dee master    
git_repo_checkout_branch "../libs/mysql"                          25f9900c0ba9b5f58d75ff86097782388979165a master    
git_repo_checkout_branch "../libs/nowide"                         7ea5d333cce9f07d09dc59272771b610c6b33126 master    
git_repo_checkout_branch "../libs/numeric/conversion"             50a1eae942effb0a9b90724323ef8f2a67e7984a master    
git_repo_checkout_branch "../libs/numeric/interval"               565d0d754f851eb9447745b359ca5be6a033918c master    
git_repo_checkout_branch "../libs/numeric/odeint"                 9e75be5d9e435739b086aee928736fc241e77a4a master    
git_repo_checkout_branch "../libs/numeric/ublas"                  15d871b410ff92592c6f3e0a53550035e7817046 master    
git_repo_checkout_branch "../libs/optional"                       121f3efde91de78ca018019904732f55d33b5788 master    
git_repo_checkout_branch "../libs/outcome"                        a3686af224a86dfcf5f12aeb039502bae82d2a6b master    
git_repo_checkout_branch "../libs/parameter"                      c142f7bdc27ed5abf945370c3bd82750fc0bdef1 master    
git_repo_checkout_branch "../libs/parameter_python"               1f7f9ce9930119f0dda7dcd5e1ec3b5ed7c6b091 master    
git_repo_checkout_branch "../libs/parser"                         f468d529fe440313d9d67d092f360b1a64a6f702 master    
git_repo_checkout_branch "../libs/pfr"                            3fe5ce61eee743c6da097c28bc0b84bdf29f6cc4 master    
git_repo_checkout_branch "../libs/phoenix"                        8913607a3788cb82d48ed461ea59c919b7bad3df master    
git_repo_checkout_branch "../libs/poly_collection"                bbdfaefc323ef1892107ae47ba87323eba4adb8b master    
git_repo_checkout_branch "../libs/polygon"                        8ba35b57c1436c4b36f7544aadd78c2b24acc7db master    
git_repo_checkout_branch "../libs/pool"                           2952382c4f54ad75cd5de3c5841132ec53927643 master    
git_repo_checkout_branch "../libs/predef"                         6364545bbabbab37ca7f6c9cedbe8a6145737feb master    
git_repo_checkout_branch "../libs/preprocessor"                   d899a718f190e9823d37411819e89e8e4e535c37 master    
git_repo_checkout_branch "../libs/process"                        fa83c2f9ffcd3bbdfa9244c777b64e3ca98c07c4 master    
git_repo_checkout_branch "../libs/program_options"                06e103d363b1380ed6c95e9cb25ab4f0ac8120bc master    
git_repo_checkout_branch "../libs/property_map"                   830cb6bce0b54fc1b2d7806901c1b8c8716964b7 master    
git_repo_checkout_branch "../libs/property_map_parallel"          a2f90e9660e4e7e012c0b54a1338d8e69fb71906 master    
git_repo_checkout_branch "../libs/property_tree"                  8080ecd14f2d952a4bb7ae869fc0f54f54f5a31f master    
git_repo_checkout_branch "../libs/proto"                          6392660ed6100285091143c95e95d2f0c532d292 master    
git_repo_checkout_branch "../libs/ptr_container"                  fa5071af867bfd2480e3b004a4bee27127b951b6 master    
git_repo_checkout_branch "../libs/python"                         ff0ae9b29d7707d63d6f0ad4a64b578021783693 master    
git_repo_checkout_branch "../libs/qvm"                            c26cbf5c0d7723dbf2e1712259c5616d15f56ffa master    
git_repo_checkout_branch "../libs/random"                         56a476afdc77327a77ecb916872788038f8cfd3b master    
git_repo_checkout_branch "../libs/range"                          2bb6b636796f7b008196888613f51f5bb347c77d master    
git_repo_checkout_branch "../libs/ratio"                          6eceadad2eb04f00b8cae5e400f7bee34c2d501f master    
git_repo_checkout_branch "../libs/rational"                       3c6dfc84c90d4dbcfa81d7dc685bcab702f3473d master    
git_repo_checkout_branch "../libs/redis"                          8df535f50ef9beaffe6721d1b78df6c9d87f502b master    
git_repo_checkout_branch "../libs/regex"                          45d6bd24cd6c50fe95ccca7ab3a9fb384beb7d10 master    
git_repo_checkout_branch "../libs/safe_numerics"                  777e0be5ec763d0333a717c5e421a4f7c5e5bdc9 master    
git_repo_checkout_branch "../libs/scope"                          650fac7419d7bc4e78df70bfe99847987bb7cbe2 master    
git_repo_checkout_branch "../libs/scope_exit"                     60baaae454b2da887a31cf939e22015b6263c9e4 master    
git_repo_checkout_branch "../libs/serialization"                  a20c4d97c37e5f437c8ba78f296830edb79cff9e master    
git_repo_checkout_branch "../libs/signals2"                       898c81affdac7759768f846ea461d2364b028f0e master    
git_repo_checkout_branch "../libs/smart_ptr"                      0b0924ff82ba78c1e6c89965abadb6fae109a4e3 master    
git_repo_checkout_branch "../libs/sort"                           420a36da32a6eaef93a5b70eabd7a5aa0ed3ae8d master    
git_repo_checkout_branch "../libs/spirit"                         43112c3f055fa109f20b8e8e6e50d0a016da742a master    
git_repo_checkout_branch "../libs/stacktrace"                     ea282324b8b8623bf0515248b525650a6e78ebdd master    
git_repo_checkout_branch "../libs/statechart"                     ae93e58e44f722626fe462a854b92d9b4f11449a master    
git_repo_checkout_branch "../libs/static_assert"                  ba72d3340f3dc6e773868107f35902292f84b07e master    
git_repo_checkout_branch "../libs/static_string"                  bff5cb65a5cb9151aacaf56abe80125e0128f43a master    
git_repo_checkout_branch "../libs/stl_interfaces"                 cefbd3014ab1b0c305c4e58f650757fa4fa81040 master    
git_repo_checkout_branch "../libs/sync"                           a75e8485cbf528253a9c9d8bee6a9fa09e337b63 master    
git_repo_checkout_branch "../libs/system"                         f1556673a1121df9fe1ac18c63bb3d0396b57c5f master    
git_repo_checkout_branch "../libs/test"                           aebe90506f653fd1380d8000309b41557d2a9d29 master    
git_repo_checkout_branch "../libs/thread"                         4db7ba2031178cc265e1e1b558c81d4f6f36443a master    
git_repo_checkout_branch "../libs/throw_exception"                f3d4d55f52894fda75ef2915dc122e3133b97b45 master    
git_repo_checkout_branch "../libs/timer"                          b7f65f09a0975f26cb294eebd8b17e91a5beff3f master    
git_repo_checkout_branch "../libs/tokenizer"                      a1207c1a424ee565344fe5ef00605cb93f5210c2 master    
git_repo_checkout_branch "../libs/tti"                            a09ad0a24c982096c102847411c37045865a8098 master    
git_repo_checkout_branch "../libs/tuple"                          f8bc34da9a0cf38a305f3cad1670200638bfb728 master    
git_repo_checkout_branch "../libs/type_erasure"                   729f3e739abc65d36d46df470c5bab735599d042 master    
git_repo_checkout_branch "../libs/type_index"                     a418e8414b7ccd3f5e4fc8595dd2ac5309b30f9b master    
git_repo_checkout_branch "../libs/type_traits"                    cc6fc3daa8e20c4a70b563d67ceb4c34d8c1c4d7 master    
git_repo_checkout_branch "../libs/typeof"                         426e7505cdca6356baca998e9e30fb148e3a78d5 master    
git_repo_checkout_branch "../libs/units"                          45787015dd8c11653eb988260acf05c4af9d42e5 master    
git_repo_checkout_branch "../libs/unordered"                      b41c054c66e7c71d6c6105a1e9da096f6731434d master    
git_repo_checkout_branch "../libs/url"                            51c9118bb4a5b5b027203d42df6ee2923a3e567a master    
git_repo_checkout_branch "../libs/utility"                        94644596c2fd429c997f5db284d669bc910b571e master    
git_repo_checkout_branch "../libs/uuid"                           e7f4cebe81835fd1b5558178f3d4c40ae266d8e2 master    
git_repo_checkout_branch "../libs/variant"                        1fd7271d2e34a36f010f8882fdde703ad9a4ffeb master    
git_repo_checkout_branch "../libs/variant2"                       8caa1a34843951b9e4e302dc85e90bc19ca4f3dd master    
git_repo_checkout_branch "../libs/vmd"                            34cad2c1a574d445812c7c2432d3a5a5c843b412 master    
git_repo_checkout_branch "../libs/wave"                           021cee734806a4ee81f9f35d784f096f7832901c master    
git_repo_checkout_branch "../libs/winapi"                         ea553ab4d2e4cba1448d23a542993692c9d385f7 master    
git_repo_checkout_branch "../libs/xpressive"                      bd1db9341abd303dacc2979422d8809a9a1e0558 master    
git_repo_checkout_branch "../libs/yap"                            ae49bf2744586e6bd6c0cedff4500a58a4386860 master    
git_repo_checkout_branch "../more"                                eaa5c0f18bee6ab33c4790921534454762b81ee0 master    
git_repo_checkout_branch "../tools/auto_index"                    91e2f15b8b1e7d609b8398286833cb9847984ecc master    
git_repo_checkout_branch "../tools/bcp"                           2bb48d28b1fb96320f2d72a9299f1e5e4d41d31d master    
git_repo_checkout_branch "../tools/boost_install"                 c9fbbd023650a85e80a649b1d5fb5c40c1fc15eb master    
git_repo_checkout_branch "../tools/boost_unordered_benchmarks"    26fcdfff4cf250aa3ed8bdc82763d7458cc39858 main      
git_repo_checkout_branch "../tools/boostbook"                     066f3561e6166dcaab2f5c1439d41ac105d8361a master    
git_repo_checkout_branch "../tools/boostdep"                      4e142024121397378e9c598ea2486c0a79c3cf5d master    
git_repo_checkout_branch "../tools/boostlook"                     35446e1a347e86c25722fdffd6de0df401645d46 master    
git_repo_checkout_branch "../tools/build"                         4a52d8c06635435b64e31a56eaf7ca5dc912a71d master    
git_repo_checkout_branch "../tools/check_build"                   092f1f300410bee1495c0b8f27d61ac32bc16c42 master    
git_repo_checkout_branch "../tools/cmake"                         7f5336b3bf8067bb40da4e8b9940c133271e938a master    
git_repo_checkout_branch "../tools/docca"                         4510773965d15735af6331a4734387d7ec7d50cf master    
git_repo_checkout_branch "../tools/inspect"                       d18744cddbd4304f7b939131004571dbb301fa4f master    
git_repo_checkout_branch "../tools/litre"                         564d4d8d30b7e03ac5e25d78e14d2c19fa321c83 master    
git_repo_checkout_branch "../tools/quickbook"                     56e4aca294d94d5fbcc19d44ea3762b9ec5e5ac9 master    

# --- all done ---

popd                                                                           2> /dev/null  > /dev/null

