#! /bin/bash
#
# Generated by the utility: /z/tools/collect_git_checked_out_branch_recusively.sh 
#
# Checkout each git repository to the given branch/commit or list them
#

mode=h;
while getopts ":hlrc" opt ; do
  #echo opt+arg = "$opt$OPTARG"
  case "$opt$OPTARG" in
  l )
    mode=l;
    ;;

  c )
    mode=c;
    ;;

  r )
    mode=r;
    ;;

  * )
    ;;
  esac
done

if test "$mode" = "h" ; then
  cat <<EOH
checkout_to_known_git_branches_recursive.sh options

Options:

-h      : print this help
-l      : LIST the branch/commit for each git repository (directory) registered in this script.
-c      : CHECKOUT each git repository to the BRANCH registered in this script.
-r      : CHECKOUT/REVERT each git repository to the COMMIT registered in this script.

Note:

Use the '-r' option to set each repository to an exact commit position, which is useful if,
for instance, you wish to reproduce this registered previous software state (which may
represent a software release) which you wish to analyze/debug.

EOH
  exit 1;
fi

if test "$mode" = "l" ; then
  cat <<EOH

Git repository directory                    :: commit hash                         / branch name
--------------------------------------------::--------------------------------------------------
EOH
fi



# args: DIR COMMIT [BRANCH]
git_repo_checkout_branch() {
  if test "$mode" = "c" || test "$mode" = "r" ; then
    if test -d "$1" ; then
      pushd "$1"                                                               2> /dev/null  > /dev/null
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
      if test "$mode" = "c" ; then
        if test -n "$3" ; then
          # make sure the branch is created locally and is a tracking branch, if it isn't already:
          # https://www.cyberciti.biz/faq/bash-remove-whitespace-from-string/
          current_branch=$( git branch --show-current )
          if test -z "$current_branch" -o "$current_branch" != "$3" ; then
            git checkout "$3"
          fi

          shopt -s extglob
          remote_branch=$( git branch -vv --list $3 '--format=%(upstream)' )
          # Trim leading whitespaces
          remote_branch="${remote_branch##*( )}"
          # Trim trailing whitespaces
          remote_branch="${remote_branch%%*( )}"
          echo "=${remote_branch}="
          shopt -u extglob

          if test -z "$remote_branch" ; then
            echo "No remote branch registered for local branch: $3 --> setting up the remote."
            git branch --track "$3" "remotes/origin/$3"                          2> /dev/null  > /dev/null
            git branch --set-upstream-to=remotes/origin/$3 $3                    2> /dev/null  > /dev/null
            git checkout "$3"
          fi
        else
          current_branch=$( git branch --show-current )
          echo "=${current_branch}="
          if test -z "$current_branch" -o "$current_branch" != "master" ; then
            # checkout to the first of `master` or `main` in case we're not checked out to either right now:
            if test "$current_branch" != "main" -a "$current_branch" != "master" ; then
              echo "Checking out to master/main:"
              git checkout master
              if test $? -ne 0 ; then
                git checkout main
              fi
            fi
          fi
        fi
      else
        git checkout "$2"
      fi
      popd                                                                     2> /dev/null  > /dev/null
    fi
  else
    if test -d "$1" ; then
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
    else
      printf "%-43s :: %s / %s\n" "[DIRECTORY DOES NOT EXIST!] $1" "$2" "$3"
    fi
  fi
}


#
# Make sure we switch to the utility directory as all the relative paths for the repositories
# are based off that path!
#
pushd $(dirname $0)                                                            2> /dev/null  > /dev/null



#
# The registered repositories:
#

git_repo_checkout_branch "../libs/accumulators"                   3f4d2564762b431cebf8dd6f45204b60e83268bc master    
git_repo_checkout_branch "../libs/algorithm"                      32c5a6327cfdca5d41ce0f1d8849b811886daa2f master    
git_repo_checkout_branch "../libs/align"                          5ad7df63cd792fbdb801d600b93cad1a432f0151 master    
git_repo_checkout_branch "../libs/any"                            9b1941c787f2769fcb6afdb0cef621db80f953a6 master    
git_repo_checkout_branch "../libs/array"                          b36532b5cfc4bf66f1d64af4425399271aec4e71 master    
git_repo_checkout_branch "../libs/asio"                           7d836dcf2496d1b883ca73afe108ca66cb65999e master    
git_repo_checkout_branch "../libs/assert"                         5dcb2af5213ae132b7531e45e7f93258cc33ffd8 master    
git_repo_checkout_branch "../libs/assign"                         b452220f5de0f6205433c08cee63742102a424d2 master    
git_repo_checkout_branch "../libs/atomic"                         11537e688cdb5fbaf0d3e554528bb751c2059053 master    
git_repo_checkout_branch "../libs/beast"                          9b24b28d502946583300d3e58767cb30a8ec8486 master    
git_repo_checkout_branch "../libs/bimap"                          f64de6d045bf6aa3f39a672604bcccbc97291525 master    
git_repo_checkout_branch "../libs/bind"                           a541a8d5c16920e1836d09299915890d687efe36 master    
git_repo_checkout_branch "../libs/bloom"                          bf22fc39abd782f18f1d68b31ff196760d038b8c master    
git_repo_checkout_branch "../libs/callable_traits"                2a56a3a2496cdb66496f844db55085dd992d5e49 master    
git_repo_checkout_branch "../libs/charconv"                       728f7c4a85d7893c91c5fd85220367bb17cd06b5 master    
git_repo_checkout_branch "../libs/chrono"                         ef510872039483dc66b7b2263c43c273a9aaecd6 master    
git_repo_checkout_branch "../libs/circular_buffer"                a08a5b55ee82e0c2487523471379ac53a23935dc master    
git_repo_checkout_branch "../libs/cobalt"                         57181cacc5b8d5079d95a33b7aa078d0f5f16147 master    
git_repo_checkout_branch "../libs/compat"                         a5a56ee5c0ed2c3b981374c17d76933bedefff71 master    
git_repo_checkout_branch "../libs/compatibility"                  7be386ad98083806f805c6d1e2450e09ae10250f master    
git_repo_checkout_branch "../libs/compute"                        cf7907574d6159cd43e6cf687a7b656278c61dd0 master    
git_repo_checkout_branch "../libs/concept_check"                  8edcb88b88470e2bb1a7e09c554e520bbe96824b master    
git_repo_checkout_branch "../libs/config"                         7abb0e12016e7b1089a9920ad3d594401e0e94fd master    
git_repo_checkout_branch "../libs/container"                      4d4c384c3e77bc67050c7928102b5c3a255bdcc3 master    
git_repo_checkout_branch "../libs/container_hash"                 060d4aea6b5b59d2c9146b7d8e994735b2c0a582 master    
git_repo_checkout_branch "../libs/context"                        3af0091efa65892e030add013417840f80b13e08 master    
git_repo_checkout_branch "../libs/contract"                       4a4047f84a1a849f8e2737d8d4ceb71a739e2082 master    
git_repo_checkout_branch "../libs/conversion"                     b74a4c34cb181a8a26d35d05fab608426449626a master    
git_repo_checkout_branch "../libs/convert"                        0dd7a76b1c051c048b4991b7aa9c8b5aeb5776ee master    
git_repo_checkout_branch "../libs/core"                           59a587639679df6645fc1cce361bec26ac2d4129 master    
git_repo_checkout_branch "../libs/coroutine"                      fea8fcc486afbcfbdec36ae39ad48e161b9afaaa master    
git_repo_checkout_branch "../libs/coroutine2"                     dbbf042e0a9081b4119d491b788ae0fe7c03192a master    
git_repo_checkout_branch "../libs/crc"                            d547322aa734b37901fa79e7b5e71040d698ce69 master    
git_repo_checkout_branch "../libs/date_time"                      3df2f6bca4b27736c8a90a9ba645cd1605bca274 master    
git_repo_checkout_branch "../libs/describe"                       5858ccb775d415283dfd77ab5aeb7035faeaab91 master    
git_repo_checkout_branch "../libs/detail"                         ae7e821d61151254ed9b5c5c886fc7ff5f300a7e master    
git_repo_checkout_branch "../libs/dll"                            c6d1c7f977c9952a3e895de15622d263eea38e9c master    
git_repo_checkout_branch "../libs/dynamic_bitset"                 b96250c3c66d310b51555fbf532245c47d71c1b9 master    
git_repo_checkout_branch "../libs/endian"                         36b37b7f727095fafae05a6feac9abc2d390465d master    
git_repo_checkout_branch "../libs/exception"                      0235ec98247ce9c7dc30d742a28c11fad779fcef master    
git_repo_checkout_branch "../libs/fiber"                          238487b543e8863c647d31a82ccfc3fa11a960d9 master    
git_repo_checkout_branch "../libs/filesystem"                     3eafca446c3af9b9033c222b37004e5f0a13f072 master    
git_repo_checkout_branch "../libs/flyweight"                      575a6852b994b1d3f3fac6b613ea7246778f8369 master    
git_repo_checkout_branch "../libs/foreach"                        904451bb8b094b426a69fbf33825c06677f2835f master    
git_repo_checkout_branch "../libs/format"                         f736a5f56de4a09e89e9c1de21c2a227be638c12 master    
git_repo_checkout_branch "../libs/function"                       f6b538dbed2e3047dcbd09eb3f5c7f1ffa90d0a9 master    
git_repo_checkout_branch "../libs/function_types"                 6fba35ace59e9e7b1c3007ca6246a42ed6ead145 master    
git_repo_checkout_branch "../libs/functional"                     6a573e4b8333ee63ee62ce95558c3667348db233 master    
git_repo_checkout_branch "../libs/fusion"                         94cab8e4bbc8065d18481b96c0a8feea0491cf6e master    
git_repo_checkout_branch "../libs/geometry"                       617d75e0cda78b1f05590319200973514b609097 master    
git_repo_checkout_branch "../libs/gil"                            c81e064234e69c40307153b1315b00aee9a22c5b master    
git_repo_checkout_branch "../libs/graph"                          0eb6022c913e6e016cd726acb9f27f9f0f1d8097 master    
git_repo_checkout_branch "../libs/graph_parallel"                 5520a5617d2763c48a06a4ff277ad76e665c7cf3 master    
git_repo_checkout_branch "../libs/hana"                           bc49ee25638e59d977edff5737b4e6bf12c1e5ea master    
git_repo_checkout_branch "../libs/hash2"                          8802ebff1040c363a39b650f4045b0c2beb516da master    
git_repo_checkout_branch "../libs/headers"                        95930ca8f5d144fe345a2ad7a2a7728b8c3e5cd5 master    
git_repo_checkout_branch "../libs/heap"                           7db5d9db6615b40239a8bb9383a12bd56924bd07 master    
git_repo_checkout_branch "../libs/histogram"                      bf4b8c258873a80d77d9628ee24d6c0d2fd439ae master    
git_repo_checkout_branch "../libs/hof"                            63ac019fca325038bfb4f56db17fbb281d2b5f49 master    
git_repo_checkout_branch "../libs/icl"                            2741c3a1b7b79f7326360c26c3e1588b385c9e53 master    
git_repo_checkout_branch "../libs/integer"                        4d702c79a45c1b204de864a5d11efa711e8713cf master    
git_repo_checkout_branch "../libs/interprocess"                   2c3d4f8bb91400298f285ebd197d808cf14b126a master    
git_repo_checkout_branch "../libs/intrusive"                      23e7a9cbf54f69f2bdc22951af959af74b037d10 master    
git_repo_checkout_branch "../libs/io"                             342e4c6d10d586058818daa84201a2d301357a53 master    
git_repo_checkout_branch "../libs/iostreams"                      3173bcac127b1e23b05d7ed07a93ad8cadc5ae3f master    
git_repo_checkout_branch "../libs/iterator"                       248494330d2d82a0264d2f93b88a92687ef7bb7e master    
git_repo_checkout_branch "../libs/json"                           3c80c097d2fe2266d3d41f4121d7af24e122e996 master    
git_repo_checkout_branch "../libs/lambda"                         3b94bb73aacd39887d9b8d50aa350f4769f6eef6 master    
git_repo_checkout_branch "../libs/lambda2"                        dddfec608515f5a4f51f86d9b8efc01c7ad816cc master    
git_repo_checkout_branch "../libs/leaf"                           aff38b5be343ac6f1588e3258d126224e5347934 master    
git_repo_checkout_branch "../libs/lexical_cast"                   4862e296d0418a1155a69c158270c560f01f54ae master    
git_repo_checkout_branch "../libs/local_function"                 9833c9396ec1cb1abc6a71bef25689f2555fb32f master    
git_repo_checkout_branch "../libs/locale"                         da39dbaf86b2f994e2ae1577d98e4be39cc683bc master    
git_repo_checkout_branch "../libs/lockfree"                       4a69f38b3d1d20ac56e60095a550ffb2ce4ccbd7 master    
git_repo_checkout_branch "../libs/log"                            a46993b0b8feb1da54566bbb306f1a7f2e793c4e master    
git_repo_checkout_branch "../libs/logic"                          9b8703a2d6623405323b892f1d126a6b17ca1651 master    
git_repo_checkout_branch "../libs/math"                           beaf8026260acec743b457f7f126922a230bcf13 master    
git_repo_checkout_branch "../libs/metaparse"                      0c7c2dd33744ad251e3124aa4f372194fd662902 master    
git_repo_checkout_branch "../libs/move"                           40d2be68bae9acfb4f165cdaab0a4246c5af5485 master    
git_repo_checkout_branch "../libs/mp11"                           1f3d0bbe0c994f8672c369294e3e6690ba3fd145 master    
git_repo_checkout_branch "../libs/mpi"                            1ed3a7cbbf9ddc7a69c5dc62296d715fc4598cda master    
git_repo_checkout_branch "../libs/mpl"                            3bc1db8b74d69b6db19e9012b061bbe55e8186ee master    
git_repo_checkout_branch "../libs/mqtt5"                          a23546c96099c172a0b4b5df063cb88920e81940 master    
git_repo_checkout_branch "../libs/msm"                            33e77cbfc70956d4b99f3dfc9c1e83848fe2550b master    
git_repo_checkout_branch "../libs/multi_array"                    0c5348bef71b890c4bd06eff1ee5ebda69e7b27a master    
git_repo_checkout_branch "../libs/multi_index"                    90697ee83e4a1c144dc54da891a0a4be61c4f8b9 master    
git_repo_checkout_branch "../libs/multiprecision"                 f719830110211cbf6df30225f028b6dc55578777 master    
git_repo_checkout_branch "../libs/mysql"                          6a82609638e88bcea2985069dfc356f32a575a55 master    
git_repo_checkout_branch "../libs/nowide"                         d940d534ef164872fd5bfa6c559be96908b7ba5f master    
git_repo_checkout_branch "../libs/numeric/conversion"             d1b479f7a4aa54d8ffb93d8dc4ee0c24670210d8 master    
git_repo_checkout_branch "../libs/numeric/interval"               565d0d754f851eb9447745b359ca5be6a033918c master    
git_repo_checkout_branch "../libs/numeric/odeint"                 9e75be5d9e435739b086aee928736fc241e77a4a master    
git_repo_checkout_branch "../libs/numeric/ublas"                  15d871b410ff92592c6f3e0a53550035e7817046 master    
git_repo_checkout_branch "../libs/optional"                       121f3efde91de78ca018019904732f55d33b5788 master    
git_repo_checkout_branch "../libs/outcome"                        9fab401aa0ee4e578ec6757c082b6f66c67a55c7 master    
git_repo_checkout_branch "../libs/parameter"                      2592296b4144a3ac7e260e69303c98aec6482123 master    
git_repo_checkout_branch "../libs/parameter_python"               1f7f9ce9930119f0dda7dcd5e1ec3b5ed7c6b091 master    
git_repo_checkout_branch "../libs/parser"                         c674e94c3d409b6ab0ee05429361e8b50fe30320 master    
git_repo_checkout_branch "../libs/pfr"                            4f9e6457b0e79df1e705e79911078d51647f88c4 master    
git_repo_checkout_branch "../libs/phoenix"                        8913607a3788cb82d48ed461ea59c919b7bad3df master    
git_repo_checkout_branch "../libs/poly_collection"                3175ae3c91203556f86561f574830aa38d5bc80c master    
git_repo_checkout_branch "../libs/polygon"                        8ba35b57c1436c4b36f7544aadd78c2b24acc7db master    
git_repo_checkout_branch "../libs/pool"                           740c8076f9d02f0216e8f3dbb15d2fd80f67d7f4 master    
git_repo_checkout_branch "../libs/predef"                         9930ae8939349db1a6b820a3399d829ba1d7d540 master    
git_repo_checkout_branch "../libs/preprocessor"                   cd1b1bd03900b68505822cfa25cb16851bd6caf1 master    
git_repo_checkout_branch "../libs/process"                        5597aa0055b81017f6ea24cb652f07a014b12771 master    
git_repo_checkout_branch "../libs/program_options"                716316e392740f7a9063df19ca7cb0add5866654 master    
git_repo_checkout_branch "../libs/property_map"                   830cb6bce0b54fc1b2d7806901c1b8c8716964b7 master    
git_repo_checkout_branch "../libs/property_map_parallel"          a2f90e9660e4e7e012c0b54a1338d8e69fb71906 master    
git_repo_checkout_branch "../libs/property_tree"                  2669458cebee100bc1f9f4a9d2f0cd95d07740bc master    
git_repo_checkout_branch "../libs/proto"                          6392660ed6100285091143c95e95d2f0c532d292 master    
git_repo_checkout_branch "../libs/ptr_container"                  fa5071af867bfd2480e3b004a4bee27127b951b6 master    
git_repo_checkout_branch "../libs/python"                         3e7be69e1e405e1d5ddd232c69c024ee441592c5 master    
git_repo_checkout_branch "../libs/qvm"                            daabde8f20ef751d078c220e230f81f7aee0db05 master    
git_repo_checkout_branch "../libs/random"                         8f9fa91d469c3ae820feceea397b4b8a1eb2f8fb master    
git_repo_checkout_branch "../libs/range"                          24b7c98ca12708549513adc4770a2cf5586168f9 master    
git_repo_checkout_branch "../libs/ratio"                          6eceadad2eb04f00b8cae5e400f7bee34c2d501f master    
git_repo_checkout_branch "../libs/rational"                       3c6dfc84c90d4dbcfa81d7dc685bcab702f3473d master    
git_repo_checkout_branch "../libs/redis"                          76129bbcb8373f23d37877fccededb288690eed0 master    
git_repo_checkout_branch "../libs/regex"                          8d8d275e1e6b249d3fd014cdf4e2a2a7048ffd07 master    
git_repo_checkout_branch "../libs/safe_numerics"                  777e0be5ec763d0333a717c5e421a4f7c5e5bdc9 master    
git_repo_checkout_branch "../libs/scope"                          edb755c829ba65e89f9d97ec3bb85c374f3a3451 master    
git_repo_checkout_branch "../libs/scope_exit"                     60baaae454b2da887a31cf939e22015b6263c9e4 master    
git_repo_checkout_branch "../libs/serialization"                  a20c4d97c37e5f437c8ba78f296830edb79cff9e master    
git_repo_checkout_branch "../libs/signals2"                       042de2b4d710ac24d39323048d9146d239603f84 master    
git_repo_checkout_branch "../libs/smart_ptr"                      aae2efdab2c53f565a37c9432f51dbb9caa8d543 master    
git_repo_checkout_branch "../libs/sort"                           241945faac206bd42a6d84dd01872280622fff37 master    
git_repo_checkout_branch "../libs/spirit"                         0b4a96dc66bcb868d812cd9cbdfc5e4f65dc169f master    
git_repo_checkout_branch "../libs/stacktrace"                     cf5992230b9077ec1d8758824cdb8acf58b71407 master    
git_repo_checkout_branch "../libs/statechart"                     ae93e58e44f722626fe462a854b92d9b4f11449a master    
git_repo_checkout_branch "../libs/static_assert"                  9a6a86efc8dea37083ed1a78fb0998673517cf4e master    
git_repo_checkout_branch "../libs/static_string"                  bff5cb65a5cb9151aacaf56abe80125e0128f43a master    
git_repo_checkout_branch "../libs/stl_interfaces"                 9bf4c9275820a3e2b59c3f4eb1dd638d8beb3386 master    
git_repo_checkout_branch "../libs/sync"                           15b407950afdc110d454a58a1c4077c68c7058be master    
git_repo_checkout_branch "../libs/system"                         bd3ccf769f7e3ea84899bc1984f03e6b356f0f75 master    
git_repo_checkout_branch "../libs/test"                           c28a007c3c33f1f79aaccbdfcee00692f52d4bbd master    
git_repo_checkout_branch "../libs/thread"                         9fad6ea6674359efb4933f598813faa6362261be master    
git_repo_checkout_branch "../libs/throw_exception"                f3d4d55f52894fda75ef2915dc122e3133b97b45 master    
git_repo_checkout_branch "../libs/timer"                          f90f2e3091d804194b0b64b49a8febfa6a8b1ff0 master    
git_repo_checkout_branch "../libs/tokenizer"                      a1207c1a424ee565344fe5ef00605cb93f5210c2 master    
git_repo_checkout_branch "../libs/tti"                            a09ad0a24c982096c102847411c37045865a8098 master    
git_repo_checkout_branch "../libs/tuple"                          d04e4a692fda32f939edede89d67e4b2234f0da9 master    
git_repo_checkout_branch "../libs/type_erasure"                   5281f14d3cb59f978c8cb6cbb90ce92dde4e3e13 master    
git_repo_checkout_branch "../libs/type_index"                     d13ba26c03e8fc612e14f2128d740ce70c51c9b9 master    
git_repo_checkout_branch "../libs/type_traits"                    e61ed8991fe96ac349ccd5163d8478c5db43a060 master    
git_repo_checkout_branch "../libs/typeof"                         26e22b8b370617a6181f3ae4bd1f584b3b4767e1 master    
git_repo_checkout_branch "../libs/units"                          45787015dd8c11653eb988260acf05c4af9d42e5 master    
git_repo_checkout_branch "../libs/unordered"                      dcc485bcb51d6d4ae18007e1de47230bc26e50a6 master    
git_repo_checkout_branch "../libs/url"                            c55196bd147cff2b890cca5e046a18a384d08743 master    
git_repo_checkout_branch "../libs/utility"                        176bac77d54b169431487daf614d422948af72d5 master    
git_repo_checkout_branch "../libs/uuid"                           bbbb20427c708c8b3528e6c6e483c0c484db20d0 master    
git_repo_checkout_branch "../libs/variant"                        9738f5733b3a9863be0cc2ab23cd9ba1ae5b74ff master    
git_repo_checkout_branch "../libs/variant2"                       8caa1a34843951b9e4e302dc85e90bc19ca4f3dd master    
git_repo_checkout_branch "../libs/vmd"                            34cad2c1a574d445812c7c2432d3a5a5c843b412 master    
git_repo_checkout_branch "../libs/wave"                           d7aa5a369d8f2faf48c8ea16ba041dfabbf91363 master    
git_repo_checkout_branch "../libs/winapi"                         094612ee33a8dce960cd075537266fdb4788d059 master    
git_repo_checkout_branch "../libs/xpressive"                      dd976aafaaba4d9e370c8bd7a573a1a197de744b master    
git_repo_checkout_branch "../libs/yap"                            2d44666933c2993c992a3fc348776ba62cafad6b master    
git_repo_checkout_branch "../more"                                25cc14cd7b38459e981f60dedf0ed8ad89861360 master    
git_repo_checkout_branch "../tools/auto_index"                    91e2f15b8b1e7d609b8398286833cb9847984ecc master    
git_repo_checkout_branch "../tools/bcp"                           f36cb0a25953b5ae1d87394d727dedb67607cd4a master    
git_repo_checkout_branch "../tools/boost_install"                 4773b4c57a17bd83eee0abc2475047a00ef57067 master    
git_repo_checkout_branch "../tools/boost_unordered_benchmarks"    26fcdfff4cf250aa3ed8bdc82763d7458cc39858 main      
git_repo_checkout_branch "../tools/boostbook"                     066f3561e6166dcaab2f5c1439d41ac105d8361a master    
git_repo_checkout_branch "../tools/boostdep"                      de60ee6f8503c798e1d21aab8574c19b00062a7f master    
git_repo_checkout_branch "../tools/boostlook"                     5454b1c0388b2c4ca2a6cac72963937de989a67d master    
git_repo_checkout_branch "../tools/build"                         be69c44857e34fae250aa1321808a05c1d88bfde master    
git_repo_checkout_branch "../tools/check_build"                   092f1f300410bee1495c0b8f27d61ac32bc16c42 master    
git_repo_checkout_branch "../tools/cmake"                         8da84d1b53cc23000e39294eeac817c8997834ca master    
git_repo_checkout_branch "../tools/docca"                         d1d822e5aa1748575f09ad47c2236ef55fcc4272 master    
git_repo_checkout_branch "../tools/inspect"                       abceea2c547805942af80f2d315080b2fb0d1a7d master    
git_repo_checkout_branch "../tools/litre"                         564d4d8d30b7e03ac5e25d78e14d2c19fa321c83 master    
git_repo_checkout_branch "../tools/quickbook"                     a2853e70bde80992a1998c3ab1e10386cc3c3bfc master    

# --- all done ---

popd                                                                           2> /dev/null  > /dev/null

