#! /bin/bash
#
# Generated by the utility: /z/tools/collect_git_checked_out_branch_recusively.sh 
#
# Checkout each git repository to the given branch/commit or list them
#

mode=h;
while getopts ":hlrc" opt ; do
  #echo opt+arg = "$opt$OPTARG"
  case "$opt$OPTARG" in
  l )
    mode=l;
    ;;

  c )
    mode=c;
    ;;

  r )
    mode=r;
    ;;

  * )
    ;;
  esac
done

if test "$mode" = "h" ; then
  cat <<EOH
checkout_to_known_git_branches_recursive.sh options

Options:

-h      : print this help 
-l      : LIST the branch/commit for each git repository (directory) registered in this script.
-c      : CHECKOUT each git repository to the BRANCH registered in this script.
-r      : CHECKOUT/REVERT each git repository to the COMMIT registered in this script.

Note:

Use the '-r' option to set each repository to an exact commit position, which is useful if,
for instance, you wish to reproduce this registered previous software state (which may 
represent a software release) which you wish to analyze/debug.

EOH
  exit 1;
fi

if test "$mode" = "l" ; then
  cat <<EOH

Git repository directory                    :: commit hash                         / branch name
--------------------------------------------::--------------------------------------------------
EOH
fi



# args: DIR COMMIT [BRANCH]
git_repo_checkout_branch() {
  if test "$mode" = "c" || test "$mode" = "r" ; then
    if test -d "$1" ; then
      pushd "$1"                                                               2> /dev/null  > /dev/null
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
      if test "$mode" = "c" ; then
        if test -n "$3" ; then
          # make sure the branch is created locally and is a tracking branch:
          git branch --track "$3" "remotes/origin/$3"                          2> /dev/null  > /dev/null
	  git branch --set-upstream-to=remotes/origin/$3 master                2> /dev/null  > /dev/null
          git checkout "$3"
        else
          git checkout master
          if test $? -ne 0 ; then
            git checkout main
          fi
        fi
      else
        git checkout "$2"
      fi
      popd                                                                     2> /dev/null  > /dev/null
    fi
  else
    if test -d "$1" ; then
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
    else
      printf "%-43s :: %s / %s\n" "[DIRECTORY DOES NOT EXIST!] $1" "$2" "$3"
    fi
  fi
}


#
# Make sure we switch to the utility directory as all the relative paths for the repositories
# are based off that path!
#
pushd $(dirname $0)                                                            2> /dev/null  > /dev/null



#
# The registered repositories:
#

git_repo_checkout_branch "../libs/accumulators"                   14c13370602fe86d134a948943958cab0921ce9c master    
git_repo_checkout_branch "../libs/algorithm"                      3b3bd8d3db43915c74d574ff36b4d945b6fc7917 master    
git_repo_checkout_branch "../libs/align"                          bef21416a3bbd46f3f5de4f9254bf4c46ec752fe master    
git_repo_checkout_branch "../libs/any"                            06eaa82dbfb6bc3e3842f9c1e1c8151f4858f56a master    
git_repo_checkout_branch "../libs/array"                          63f83dc350b654172ad04cc719daea0f3643f83c master    
git_repo_checkout_branch "../libs/asio"                           e929e5cffa15f1813be1b0ea3b999d07d46016b9 master    
git_repo_checkout_branch "../libs/assert"                         f1a6f9ffd1a0161fc18fad36829033c570cf5ac3 master    
git_repo_checkout_branch "../libs/assign"                         e764ac1ca08daa46b4609a99895fe4874b8dc53b master    
git_repo_checkout_branch "../libs/atomic"                         a17267547071e0dd60c81945bcb6bf0162a5db07 master    
git_repo_checkout_branch "../libs/beast"                          17141a331ad4943e76933e4db51ef48a170aaf84 master    
git_repo_checkout_branch "../libs/bimap"                          85f0f02537d71794a415ef4b992629b2edebfbff master    
git_repo_checkout_branch "../libs/bind"                           edc56d844225106a13334fefb2bfcbbfdb8e8d84 master    
git_repo_checkout_branch "../libs/callable_traits"                2a56a3a2496cdb66496f844db55085dd992d5e49 master    
git_repo_checkout_branch "../libs/chrono"                         5885f9ef0e02b2be1730380c99b2cde3d03cdcd1 master    
git_repo_checkout_branch "../libs/circular_buffer"                d4fbf446b903fb6651b56bbd5931a9b902ef962c master    
git_repo_checkout_branch "../libs/compatibility"                  47ce71af6b018764c9ba74c0bfcb4f3151b81aa7 master    
git_repo_checkout_branch "../libs/compute"                        36350b7de849300bd3d72a05d8bf890ca405a014 master    
git_repo_checkout_branch "../libs/concept_check"                  e34c735a1a6902de0d3e20ea58cfd8f101702458 master    
git_repo_checkout_branch "../libs/config"                         ccb115fe5f00bb360e404f0cef76f687c714f2c4 master    
git_repo_checkout_branch "../libs/container"                      34cd4142804556221fae9012814466210f5eda94 master    
git_repo_checkout_branch "../libs/container_hash"                 53c12550fa11221975f58a6c23581b4563153e04 master    
git_repo_checkout_branch "../libs/context"                        fb8cda1274b0e73e5ad1a9adaa4127bc2a2141b4 master    
git_repo_checkout_branch "../libs/contract"                       eca93d24b5d3bb909ed64c12b5feb5296c5cc070 master    
git_repo_checkout_branch "../libs/conversion"                     4ae8b4d49547126264f0b80c528fcfd26cdf5e7d master    
git_repo_checkout_branch "../libs/convert"                        39bcd6e60c3a74c15689d4b2db612f8fe654161d master    
git_repo_checkout_branch "../libs/core"                           ac9d79992e0f5bcdb8953330c67fe9c706c9f79f master    
git_repo_checkout_branch "../libs/coroutine"                      1e1347c0b1910b9310ec1719edad8b0bf2fd03c8 master    
git_repo_checkout_branch "../libs/coroutine2"                     d7e1c1c4abcf8c1e90097279e485edea0b253a80 master    
git_repo_checkout_branch "../libs/crc"                            96daae9fcdf965298077ed12a9304ea24713bb40 master    
git_repo_checkout_branch "../libs/date_time"                      b280ef1506dbf3a927750cb6c4631b9b2e552768 master    
git_repo_checkout_branch "../libs/describe"                       ef9c38f90c876b7bcb98d4280d7f79684afeb6fc master    
git_repo_checkout_branch "../libs/detail"                         8c603a1894ec1d8abc7a0a538297923b0ac98b33 master    
git_repo_checkout_branch "../libs/dll"                            9f9471cc3351273d73c2cd7328d37010f5708115 master    
git_repo_checkout_branch "../libs/dynamic_bitset"                 abd641709012afffdac5a9d4887913a06e840508 master    
git_repo_checkout_branch "../libs/endian"                         0dab6737ebd60e49bb1bede55c85a191a90010e5 master    
git_repo_checkout_branch "../libs/exception"                      54f2228f78dae86335558e67cbec496693907bfc master    
git_repo_checkout_branch "../libs/fiber"                          db44baba883b8da4dd5c03f6d6248f50be61840a master    
git_repo_checkout_branch "../libs/filesystem"                     af479857cf3ade1022ea598b8464cf8e00d27bcc master    
git_repo_checkout_branch "../libs/flyweight"                      af4fd3e8eb532099cec51bb6f199029b65e7998d master    
git_repo_checkout_branch "../libs/foreach"                        cc2f75ae30492b9de69b3b692f5c59afcb7dea5e master    
git_repo_checkout_branch "../libs/format"                         9735aeda098148104b6c0b5189115479aff92b80 master    
git_repo_checkout_branch "../libs/function"                       16fca8368b5da14c4bcad977c2738dc6e482e1b7 master    
git_repo_checkout_branch "../libs/function_types"                 895335874d67987ada0d8bf6ca1725e70642ed49 master    
git_repo_checkout_branch "../libs/functional"                     075c2e089a50d6a2f566d0415c62aa9a6e09f765 master    
git_repo_checkout_branch "../libs/fusion"                         500e4c120ff2f2414ec225a2a42eb1a665c79956 master    
git_repo_checkout_branch "../libs/geometry"                       00edbf6fca86f67d86f2ebf962ebb4c373e8ee45 master    
git_repo_checkout_branch "../libs/gil"                            b29f3da72cae2354a9249268899b81417474e5b0 master    
git_repo_checkout_branch "../libs/graph"                          c583bfa197ba324806dfb10db99c76daa8ff2fd0 master    
git_repo_checkout_branch "../libs/graph_parallel"                 5520a5617d2763c48a06a4ff277ad76e665c7cf3 master    
git_repo_checkout_branch "../libs/hana"                           998033e9dba8c82e3c9496c274a3ad1acf4a2f36 master    
git_repo_checkout_branch "../libs/headers"                        017c3cd1338b5437f28506cd14119b7dcfb1a86d master    
git_repo_checkout_branch "../libs/heap"                           dc2f19f8815cbe0654df61bfc5f31ad8b06fc883 master    
git_repo_checkout_branch "../libs/histogram"                      d736aab212091864d3624a6d6c3a1f127145fdb7 master    
git_repo_checkout_branch "../libs/hof"                            0a28586156eb6cc7db1fbe74ae2a220daf40df14 master    
git_repo_checkout_branch "../libs/icl"                            e6c06ddee1e2320f11c4ec5cd2661c4abe9bca53 master    
git_repo_checkout_branch "../libs/integer"                        c6592552899cbdf11f4c00c2321ed404c79348d5 master    
git_repo_checkout_branch "../libs/interprocess"                   c4a046793e07ac171ffba395402f8c9a6011cfc2 master    
git_repo_checkout_branch "../libs/intrusive"                      f439778dc7a851bf3ba8929fd5ecf199b0d13dcd master    
git_repo_checkout_branch "../libs/io"                             932dd480263d06d00bf4b40a323dc3f4ace266e2 master    
git_repo_checkout_branch "../libs/iostreams"                      537693d1d462913053b340d37f9326104b0758ed master    
git_repo_checkout_branch "../libs/iterator"                       85d935bf6869522bd96880195bde60a185315040 master    
git_repo_checkout_branch "../libs/json"                           5874418faa12490eff3e51cb84fb197ca0f898bc master    
git_repo_checkout_branch "../libs/lambda"                         ac26514243521513d33be23aaa92a85b858ddf51 master    
git_repo_checkout_branch "../libs/lambda2"                        fd1a3e45437d643430e9a737bbe387d5d7d3bdb0 master    
git_repo_checkout_branch "../libs/leaf"                           e16e0cf417463ec992846078099d317495c2bc5e master    
git_repo_checkout_branch "../libs/lexical_cast"                   a9f296115967335aaa9f4a4cadfd900f131a60d1 master    
git_repo_checkout_branch "../libs/local_function"                 099e96bef0e5f2d513940c5987958121ca6f6e02 master    
git_repo_checkout_branch "../libs/locale"                         5789ae2532abbc3d9f5908b7c71ab079455d75a5 master    
git_repo_checkout_branch "../libs/lockfree"                       fdd4d0632dd0904f6e9c656c45397fe8ef985bc9 master    
git_repo_checkout_branch "../libs/log"                            fa675cca2b58d6c087fc63de56e894fa7fb607f3 master    
git_repo_checkout_branch "../libs/logic"                          7d15cffe159219e0b0ec58135a2f8fb3de7028e1 master    
git_repo_checkout_branch "../libs/math"                           db2a7cbb44a84c4c9cba62232c07f18b22bd965d master    
git_repo_checkout_branch "../libs/metaparse"                      0ef448c1a7ce22b5de514f9cd504c323c28f4379 master    
git_repo_checkout_branch "../libs/move"                           19bb08cf17cffba726875a906ba0be8fdfa15cd0 master    
git_repo_checkout_branch "../libs/mp11"                           590df5e0bcdf0c17911c28098b9e4a7839a63019 master    
git_repo_checkout_branch "../libs/mpi"                            79e261101a13789ee88e793c5ad406ca893c22a7 master    
git_repo_checkout_branch "../libs/mpl"                            8f10d06b9637a67b23a3a11791de5bd6bcd2e112 master    
git_repo_checkout_branch "../libs/msm"                            03f58ead6d0ec23d52e5c7b382e2c98df1d943d5 master    
git_repo_checkout_branch "../libs/multi_array"                    0c5348bef71b890c4bd06eff1ee5ebda69e7b27a master    
git_repo_checkout_branch "../libs/multi_index"                    90ad6104fe59eb694ebe9d4d864932cef7abc035 master    
git_repo_checkout_branch "../libs/multiprecision"                 6752d07d4cc926df886718aecccc9fcd167adc33 master    
git_repo_checkout_branch "../libs/nowide"                         3b120f10e427b3b8cf96b12810c1533e0b74edd3 master    
git_repo_checkout_branch "../libs/numeric/conversion"             db44689f4f4f74d6572a868e13f523c82fca5a55 master    
git_repo_checkout_branch "../libs/numeric/interval"               252c6fd6360bfb6ae51eea2ca97f324b995519e0 master    
git_repo_checkout_branch "../libs/numeric/odeint"                 db8f91a51da630957d6bfa1ff87be760b0be97a6 master    
git_repo_checkout_branch "../libs/numeric/ublas"                  f0e55caf310d5e01c7e9f2190b2422e113ddeedb master    
git_repo_checkout_branch "../libs/optional"                       3038bdea4ba0d4769c6198d45c8c82cf57294659 master    
git_repo_checkout_branch "../libs/outcome"                        338f8c4d17cedac735c056304dee2615d6ca05e6 master    
git_repo_checkout_branch "../libs/parameter"                      c82f2ec688988dac839cf8fe4eb06153bf69a641 master    
git_repo_checkout_branch "../libs/parameter_python"               1f7f9ce9930119f0dda7dcd5e1ec3b5ed7c6b091 master    
git_repo_checkout_branch "../libs/pfr"                            8a8b5bc8d3ff673c4b278d145f6bf6973844d8e9 master    
git_repo_checkout_branch "../libs/phoenix"                        15500aec2187ab59e51d05addab0fdba7e788dbb master    
git_repo_checkout_branch "../libs/poly_collection"                0b8bfc4cff012d0f23049fc5a0009ac4abadceb4 master    
git_repo_checkout_branch "../libs/polygon"                        8ba35b57c1436c4b36f7544aadd78c2b24acc7db master    
git_repo_checkout_branch "../libs/pool"                           f2b8fec976e24367b9fb6a9748c9c0071302ba55 master    
git_repo_checkout_branch "../libs/predef"                         392e4e767469e3469c9390f0d9cca16724dc3fc8 master    
git_repo_checkout_branch "../libs/preprocessor"                   d4e82d7d3f2e2adbe280966ac51ce8f9372f5a44 master    
git_repo_checkout_branch "../libs/process"                        ee945a6b9524fe59f3985c9a8c3d74944ce4f99f master    
git_repo_checkout_branch "../libs/program_options"                7bcbb4ea23c958800694436b411669f80c543e18 master    
git_repo_checkout_branch "../libs/property_map"                   427fc05576cf1802176d268b29b212d870d22e17 master    
git_repo_checkout_branch "../libs/property_map_parallel"          a2f90e9660e4e7e012c0b54a1338d8e69fb71906 master    
git_repo_checkout_branch "../libs/property_tree"                  d30ff9404bd6af5cc8922a177865e566f4846b19 master    
git_repo_checkout_branch "../libs/proto"                          7f924934689b940f3a72212ab0f714ec6fd6e34b master    
git_repo_checkout_branch "../libs/ptr_container"                  943730c349f5af0814cc16c44d63850de5bfc697 master    
git_repo_checkout_branch "../libs/python"                         8dd151177374dbf0aa5cb86bd350cf1ad13e2160 master    
git_repo_checkout_branch "../libs/qvm"                            5791440b346232c391ab8d16f559ca5b2d7ae9b3 master    
git_repo_checkout_branch "../libs/random"                         a2740d4b30178cb187fabca163e5be7803a577b9 master    
git_repo_checkout_branch "../libs/range"                          88c6199aedf8bbb5a6a8966e534f9de99943cde2 master    
git_repo_checkout_branch "../libs/ratio"                          00073b7d5896603b2036a334253dc9784285355c master    
git_repo_checkout_branch "../libs/rational"                       564623136417068916495e2b24737054d607347c master    
git_repo_checkout_branch "../libs/regex"                          a851f2141f644eb7cd9cdbe086c36491e52cbfb2 master    
git_repo_checkout_branch "../libs/safe_numerics"                  777e0be5ec763d0333a717c5e421a4f7c5e5bdc9 master    
git_repo_checkout_branch "../libs/scope_exit"                     60baaae454b2da887a31cf939e22015b6263c9e4 master    
git_repo_checkout_branch "../libs/serialization"                  0ca603daf99888bf059c01ae1bab1b27dbc35ebe master    
git_repo_checkout_branch "../libs/signals2"                       49ed1573fa91bb8c60d0a20a5d5e36d8b6d94ea9 master    
git_repo_checkout_branch "../libs/smart_ptr"                      59b5b17e813c238187d568450b7155e7398fdf18 master    
git_repo_checkout_branch "../libs/sort"                           72a3ae870c59980dadd757f5f63e6be16ab61c1b master    
git_repo_checkout_branch "../libs/spirit"                         5498bc0fd149a50fa3a52bd319eef3d9dcc3af9c master    
git_repo_checkout_branch "../libs/stacktrace"                     75b7986f9799184ecd679d86273532cb54e6a0dc master    
git_repo_checkout_branch "../libs/statechart"                     586445b824c5cf0e7e6ce4ff2df620fda5d0f0d7 master    
git_repo_checkout_branch "../libs/static_assert"                  ba72d3340f3dc6e773868107f35902292f84b07e master    
git_repo_checkout_branch "../libs/static_string"                  5d6fefdd2acd70c34d8ba4590ab888d8481532af master    
git_repo_checkout_branch "../libs/stl_interfaces"                 24f9450297cb6dc4eb9df019cd9a1c7f4379e720 master    
git_repo_checkout_branch "../libs/system"                         cb8eba7a7fef7ee8efd6c7efb221c1d28b5165d0 master    
git_repo_checkout_branch "../libs/test"                           d2895ebfdfdf16074c58c9801d53e190c4654fcb master    
git_repo_checkout_branch "../libs/thread"                         1de55fceda1829fa3b29fcfd4efe8f94de0a01d1 master    
git_repo_checkout_branch "../libs/throw_exception"                f2b76550169351edf3f4bd37998e9e03ff0d5f94 master    
git_repo_checkout_branch "../libs/timer"                          9ee4c9cd9dec4f4ab5c38ffb9cb9978427916ee0 master    
git_repo_checkout_branch "../libs/tokenizer"                      0445694a4f04caa1faa99794053684d12c621a39 master    
git_repo_checkout_branch "../libs/tti"                            03734c54a51b6372ac3296d2fe5103b7360bcd3f master    
git_repo_checkout_branch "../libs/tuple"                          500e4fa0a2845b96c0dd919e7485e0f216438a01 master    
git_repo_checkout_branch "../libs/type_erasure"                   fc39ca9936bd7ac37afa8fadf3be3b62ee378f39 master    
git_repo_checkout_branch "../libs/type_index"                     cca370a91834d331e3143ac4d023fb0f178e512b master    
git_repo_checkout_branch "../libs/type_traits"                    d2a4a6bf0a3900e11faaf6904b95183115bac54d master    
git_repo_checkout_branch "../libs/typeof"                         46c7a05f826fc020ee88210ea2a5cd9278b930ab master    
git_repo_checkout_branch "../libs/units"                          45787015dd8c11653eb988260acf05c4af9d42e5 master    
git_repo_checkout_branch "../libs/unordered"                      6e3dcfddb0500adc2574bb530ae054427dcb62a7 master    
git_repo_checkout_branch "../libs/utility"                        06548cf5fab6d910abd2173b04eb9419a843cb4a master    
git_repo_checkout_branch "../libs/uuid"                           bd835638a5179cc1fb55b9f95377bedce4e47e1d master    
git_repo_checkout_branch "../libs/variant"                        d2fdf2384b146b0c764077f5539f5f6ed7c40f20 master    
git_repo_checkout_branch "../libs/variant2"                       d34658f4c8480c3a71fb435121f68e25ca166eab master    
git_repo_checkout_branch "../libs/vmd"                            34cad2c1a574d445812c7c2432d3a5a5c843b412 master    
git_repo_checkout_branch "../libs/wave"                           c524b58847ce7c6948260bc422422b54096008b2 master    
git_repo_checkout_branch "../libs/winapi"                         7a37250e1364aa99ae3db20ee6843b0c2c57a895 master    
git_repo_checkout_branch "../libs/xpressive"                      4679fbd23f962bfa78d44acf5fa48f6f790642c0 master    
git_repo_checkout_branch "../libs/yap"                            ae49bf2744586e6bd6c0cedff4500a58a4386860 master    
git_repo_checkout_branch "../more"                                631827729ba7dbed212697ab0f6d61a0748d00a5 master    
git_repo_checkout_branch "../tools/auto_index"                    e98a81769364f56b272e510c876df874af514b29 master    
git_repo_checkout_branch "../tools/bcp"                           a86fdce7885babae3ff625de36aa2dfacf983f8c master    
git_repo_checkout_branch "../tools/boost_install"                 85e1406a570cb8aa13c8b1f885f7cc2a9982c783 master    
git_repo_checkout_branch "../tools/boostbook"                     a6701f5d278daba797697a1e5000ee41f25bcaff master    
git_repo_checkout_branch "../tools/boostdep"                      7f601b865a80db5854523d114ad7539c1e14fe18 master    
git_repo_checkout_branch "../tools/build"                         d4352f0b1de0d28977f3d488c9be0c29fd1e6f9d master    
git_repo_checkout_branch "../tools/check_build"                   9c3fc263fc3203e566c4b632c1b124e57dafbed5 master    
git_repo_checkout_branch "../tools/cmake"                         867da2bf4d4304cb2f40c8b8893f943d318bdc38 master    
git_repo_checkout_branch "../tools/docca"                         2118ea9fdbbc024503ebc8cdec87e7e52782a567 master    
git_repo_checkout_branch "../tools/inspect"                       db423bf897bcc6aa34231e5266442b75ee2a5666 master    
git_repo_checkout_branch "../tools/litre"                         564d4d8d30b7e03ac5e25d78e14d2c19fa321c83 master    
git_repo_checkout_branch "../tools/quickbook"                     5f2e8c24cb813b4b0b94d3316e664b971c5b71dd master    

# --- all done ---

popd                                                                           2> /dev/null  > /dev/null

