name: Build Static Libs (Release/x64) 

on:
  push:
    tags:
      - build_*

env:  
  GITHUB_REF_NAME: ${{ github.ref_name }}
  BUILD_TOOLSET: msvc-14.3
  BUILD_LINK_MODE: static

jobs:
  Build-Static-Libs:
    runs-on: windows-latest
    steps:
      - name: Set Build Version
        run: |
          echo ("BUILD_VER=" + $Env:GITHUB_REF_NAME.replace('build_', '')) >> $Env:GITHUB_ENV

      - name: Show Me
        run: |
          echo "$Env:BUILD_VER"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: boost-${{ env.BUILD_VER }}

      - name: Fix Submodule URL
        run: |
          (Get-Content .gitmodules).replace('url = ..', 'url = https://github.com/boostorg') | Set-Content .gitmodules

      - name: Download Submodule(s)
        run: |
          git submodule update --init --recursive

      - name: Configure Boost
        run: |
          .\bootstrap.bat

      - name: Build Boost
        run: |
          .\b2 --with-thread toolset=$Env:BUILD_TOOLSET link=$Env:BUILD_LINK_MODE threading=multi runtime-link=$Env:BUILD_LINK_MODE variant=release stage

      